version: "3.8"
services:
  db:
    container_name: CockorachDB_SingleNode
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - 26257:26257
    volumes:
          - ${PWD}/Local/SingleNode/CockroachDB/cockroach-data/:/cockroach/cockroach-data

