version: "3.8"
services:
  db:
    container_name: MySQL_SingleNode
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
